### ISSUE TITLE
Autocomplete and ADMIN_1 woe type features

### ISSUE THREAD

**Issue by rschreijer** [foursquare/twofishes#28]
Nice tool!
I've been playing around with twofishes for a few days now. I am noticing that some states in the US aren't ever suggested when using autocomplete:

http://demo.twofishes.net/?autocomplete=true&query=maine&maxInterpretations=4&woeRestrict=8

but this works:
http://demo.twofishes.net/?query=maine&maxInterpretations=4&woeRestrict=8

Same in general for two letter abbreviations:
http://demo.twofishes.net/?autocomplete=true&query=NY&maxInterpretations=4&woeRestrict=8

vs.

http://demo.twofishes.net/?query=NY&maxInterpretations=4&woeRestrict=8

Is this intended?

**Comment by jordanderson** [comment]
I've been trying to workaround this behavior, too, without rebuilding the index. For example, I would like this autocomplete query to return 'Fort Greene, Brooklyn' in the results: http://demo.twofishes.net/?autocomplete=true&query=fort%20&maxInterpretations=5&autocompleteBias=LOCAL&ll=40.689,-73.95&debug=1&woeRestrict=7,22

Is it possible to get Fort Greene into that set of 59 featureIds examined against parse? I thought that I might be able to use a hotfix to increase its population or manual boost enough to get into that set, but it doesn't appear that hotfixes are taken account during the prefix index lookup.

**Comment by rahulpratapm** [comment]
There are a couple of ways you can do this:
1. Add a boost for Fort Greene in data/custom/boosts.txt and rebuild your index. This will be considered at the time of prefix index creation.
2. This is much hackier but also faster: So, the reason adding the boost via a hotfix doesn't work is because that doesn't actually change a name, so it doesn't make it into the in-memory lookaside hotfix prefix index (you could argue that's a bug and I might agree). What you could do, however, is alter the name itself in a hotfix, e.g. by changing a flag or something. That will add it to the hotfix name and prefix indexes and (unfairly, if you think about it, but conveniently in this case) cause it to be considered in addition to the 50 features in the regular index.

**Comment by rahulpratapm** [comment]
Oops. In #1 above, I meant data/private/boosts.txt. That way it stays out of source control and doesn't affect anyone else using public twofishes.

**Comment by jordanderson** [comment]
Interesting - thank you for the hint @rahulpratapm!
